### PR TITLE
update total cases casablanca

### PR DESCRIPTION
**Pull request by messaddek**

### CODE REVIEW

**Comment by aboullaite** [comment]
@messaddek thanks for catching this! however the total number is correct (20), what is wrong is the `Active cases` only 16 and not 26! Could you update your PR accordingly  ?

**Comment by aboullaite** [comment]
I updated it! thank you

**Comment by messaddek** [comment]
could you please check the result of your repo?
http://covid19-morocco.essaddek.com/

**Comment by aboullaite** [comment]
looks good!

**Pull request merged**
