### PR TITLE
Add the epidemic response fund

### PR DESCRIPTION
**Pull request by zettalla**

### CODE REVIEW

**Comment by aboullaite** [comment]
Thanks a lot @zettalla for you contribution! I think it would be better to create a dedicated file for this subject, as it could grow over time and we can add more ressources to it ? Wdyt ?

**Comment by zettalla** [comment]
> Thanks a lot @zettalla for you contribution! I think it would be better to create a dedicated file for this subject, as it could grow over time and we can add more ressources to it ? Wdyt ?

**Comment by aboullaite** [comment]
Thanks a lot @zettalla for you contribution

**Comment by zettalla** [comment]
You're welcome it will be updated chef

**Pull request merged**
